# Workflow to keep action docs up to date

name: 'Action docs'
on:
  push:
    branches:
      - main
      - update-docs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: npalm/action-docs-action@v1.4.0

      - name: Update readme in the repository
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "chore(ci): Updating readme"
          file_pattern: README.md

